import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ContextProvider from "@/provider/ReownAppkitProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-[#181c1e] text-white`}
      >
        <ContextProvider>
          {children}
          <Toaster
            toastOptions={{
              success: {
                style: {
                  background: "green",
                  color: "white",
                  height: "40px",
                  padding: "0px 20px",
                },
              },
              error: {
                style: {
                  background: "red",
                  color: "white",
                },
              },
            }}
          />
        </ContextProvider>
      </body>
    </html>
  );
}
